version: "3.8"
services:
  appserver:
    container_name: server2
    image: vladkost/backend:v1.0.3
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy  
    restart: on-failure              

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Unix11
      MYSQL_DATABASE: students
      MYSQL_USER: students
      MYSQL_PASSWORD: Unix11
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    privileged: true
    healthcheck:                    
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pUnix11"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
