
version: 3
services:
  appserver:
    container_name: server
    image: vladkost/backend:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Unix12
      MYSQL_DATABASE: employees
      MYSQL_USER: employees
      MYSQL_PASSWORD: Unix12
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    privileged: true

